In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [4]:
torch.manual_seed(22)

In [5]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [6]:
# 모델을 선언 및 초기화. 단순 선형 회귀이므로 input_dim=1, output_dim=1.
model = nn.Linear(1,1)

In [7]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.2682]], requires_grad=True), Parameter containing:
tensor([0.4050], requires_grad=True)]


In [8]:
# optimizer 설정. 경사 하강법 SGD를 사용하고 learning rate를 의미하는 lr은 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [9]:
# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 20.498011
Epoch  100/2000 Cost: 0.122468
Epoch  200/2000 Cost: 0.075678
Epoch  300/2000 Cost: 0.046764
Epoch  400/2000 Cost: 0.028897
Epoch  500/2000 Cost: 0.017857
Epoch  600/2000 Cost: 0.011034
Epoch  700/2000 Cost: 0.006819
Epoch  800/2000 Cost: 0.004213
Epoch  900/2000 Cost: 0.002604
Epoch 1000/2000 Cost: 0.001609
Epoch 1100/2000 Cost: 0.000994
Epoch 1200/2000 Cost: 0.000614
Epoch 1300/2000 Cost: 0.000380
Epoch 1400/2000 Cost: 0.000235
Epoch 1500/2000 Cost: 0.000145
Epoch 1600/2000 Cost: 0.000090
Epoch 1700/2000 Cost: 0.000055
Epoch 1800/2000 Cost: 0.000034
Epoch 1900/2000 Cost: 0.000021
Epoch 2000/2000 Cost: 0.000013


In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [11]:
torch.manual_seed(22)

In [12]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [13]:
# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim=3, output_dim=1.
model = nn.Linear(3,1)

In [14]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1548,  0.2339, -0.2190]], requires_grad=True), Parameter containing:
tensor([-0.5661], requires_grad=True)]


In [15]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [16]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 34218.269531
Epoch  100/2000 Cost: 5.249139
Epoch  200/2000 Cost: 4.986011
Epoch  300/2000 Cost: 4.736746
Epoch  400/2000 Cost: 4.500576
Epoch  500/2000 Cost: 4.276866
Epoch  600/2000 Cost: 4.064926
Epoch  700/2000 Cost: 3.864183
Epoch  800/2000 Cost: 3.673974
Epoch  900/2000 Cost: 3.493804
Epoch 1000/2000 Cost: 3.323111
Epoch 1100/2000 Cost: 3.161422
Epoch 1200/2000 Cost: 3.008219
Epoch 1300/2000 Cost: 2.863081
Epoch 1400/2000 Cost: 2.725584
Epoch 1500/2000 Cost: 2.595313
Epoch 1600/2000 Cost: 2.471924
Epoch 1700/2000 Cost: 2.354998
Epoch 1800/2000 Cost: 2.244226
Epoch 1900/2000 Cost: 2.139297
Epoch 2000/2000 Cost: 2.039867
