In [1]:
import torch
import torch.nn.functional as F

In [2]:
torch.manual_seed(22)

In [3]:
z = torch.FloatTensor([1,2,3])

In [4]:
hypothesis = F.softmax(z, dim=0)
print(hypothesis)

tensor([0.0900, 0.2447, 0.6652])


In [5]:
hypothesis.sum()

tensor(1.)

In [6]:
z = torch.rand(3,5,requires_grad=True)

In [7]:
hypothesis = F.softmax(z, dim=1)
print(hypothesis)

tensor([[0.1857, 0.2600, 0.1757, 0.1300, 0.2486],
        [0.1192, 0.2539, 0.1954, 0.2222, 0.2093],
        [0.2366, 0.2224, 0.1445, 0.1196, 0.2769]], grad_fn=<SoftmaxBackward0>)


In [8]:
y = torch.randint(5, (3,)).long()
print(y)

tensor([4, 4, 0])


In [9]:
y_one_hot = torch.zeros_like(hypothesis)
y_one_hot.scatter_(1, y.unsqueeze(1), 1)

tensor([[0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0.]])

In [10]:
cost = (y_one_hot * -torch.log(hypothesis)).sum(dim=1).mean()
print(cost)

tensor(1.4658, grad_fn=<MeanBackward0>)


In [11]:
torch.log(F.softmax(z,dim=1))

tensor([[-1.6837, -1.3471, -1.7392, -2.0399, -1.3919],
        [-2.1268, -1.3709, -1.6327, -1.5041, -1.5640],
        [-1.4415, -1.5033, -1.9343, -2.1235, -1.2841]], grad_fn=<LogBackward0>)

In [12]:
F.log_softmax(z,dim=1)

tensor([[-1.6837, -1.3471, -1.7392, -2.0399, -1.3919],
        [-2.1268, -1.3709, -1.6327, -1.5041, -1.5640],
        [-1.4415, -1.5033, -1.9343, -2.1235, -1.2841]],
       grad_fn=<LogSoftmaxBackward0>)

In [13]:
(y_one_hot * -torch.log(F.softmax(z, dim=1))).sum(dim=1).mean()

tensor(1.4658, grad_fn=<MeanBackward0>)

In [14]:
(y_one_hot * -F.log_softmax(z, dim=1)).sum(dim=1).mean()

tensor(1.4658, grad_fn=<MeanBackward0>)

In [15]:
F.nll_loss(F.log_softmax(z,dim=1),y)

tensor(1.4658, grad_fn=<NllLossBackward0>)

In [16]:
F.cross_entropy(z,y)

tensor(1.4658, grad_fn=<NllLossBackward0>)