In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(22)

In [3]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [4]:
model = nn.Sequential(
    nn.Linear(2,1),
    nn.Sigmoid()
)

In [5]:
optimizer = optim.SGD(model.parameters(),lr=1)

nb_epochs = 1000
for epoch in range(nb_epochs+1):

  hyporthesis = model(x_train)
  cost = F.binary_cross_entropy(hyporthesis, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 50 ==0:
    prediction = hyporthesis >= torch.Tensor([0.5])
    correct_prediction = prediction.float() == y_train
    accuracy = correct_prediction.sum().item() / len(correct_prediction)

    print('Epoch {:4d}/{} Cost: (:.6f) Accuracy {:2.2f}%'.format(
        epoch, cost, accuracy
    ))

Epoch    0/0.8123920559883118 Cost: (:.6f) Accuracy 0.17%
Epoch   50/0.29171204566955566 Cost: (:.6f) Accuracy 0.83%
Epoch  100/0.1315016895532608 Cost: (:.6f) Accuracy 1.00%
Epoch  150/0.09894358366727829 Cost: (:.6f) Accuracy 1.00%
Epoch  200/0.07950683683156967 Cost: (:.6f) Accuracy 1.00%
Epoch  250/0.06656989455223083 Cost: (:.6f) Accuracy 1.00%
Epoch  300/0.05732187628746033 Cost: (:.6f) Accuracy 1.00%
Epoch  350/0.05037085339426994 Cost: (:.6f) Accuracy 1.00%
Epoch  400/0.04494881257414818 Cost: (:.6f) Accuracy 1.00%
Epoch  450/0.04059714078903198 Cost: (:.6f) Accuracy 1.00%
Epoch  500/0.037024807184934616 Cost: (:.6f) Accuracy 1.00%
Epoch  550/0.034037996083498 Cost: (:.6f) Accuracy 1.00%
Epoch  600/0.03150251880288124 Cost: (:.6f) Accuracy 1.00%
Epoch  650/0.029322540387511253 Cost: (:.6f) Accuracy 1.00%
Epoch  700/0.02742754854261875 Cost: (:.6f) Accuracy 1.00%
Epoch  750/0.025764867663383484 Cost: (:.6f) Accuracy 1.00%
Epoch  800/0.02429390512406826 Cost: (:.6f) Accuracy 1.00

In [6]:
print(model(x_train))
print(model(x_train).float()>=torch.FloatTensor([0.5]))
print(list(model.parameters()))

tensor([[2.7420e-04],
        [3.1508e-02],
        [3.8846e-02],
        [9.5635e-01],
        [9.9824e-01],
        [9.9969e-01]], grad_fn=<SigmoidBackward0>)
tensor([[False],
        [False],
        [False],
        [ True],
        [ True],
        [ True]])
[Parameter containing:
tensor([[3.2562, 1.5196]], requires_grad=True), Parameter containing:
tensor([-14.4969], requires_grad=True)]
